In [2]:
import numpy as np

### 3.1 - Zero-Padding

Zero-padding adds zeros around the border of an image:

<img src="images/PAD.png" style="width:600px;height:400px;">
<caption><center> <u> <font color='purple'> **Figure 1** </u><font color='purple'>  : **Zero-Padding**<br> Image (3 channels, RGB) with a padding of 2. </center></caption>

The main benefits of padding are the following:

- It allows you to use a CONV layer without necessarily shrinking the height and width of the volumes. This is important for building deeper networks, since otherwise the height/width would shrink as you go to deeper layers. An important special case is the "same" convolution, in which the height/width is exactly preserved after one layer. 

- It helps us keep more of the information at the border of an image. Without padding, very few values at the next layer would be affected by pixels as the edges of an image.

**Exercise**: Implement the following function, which pads all the images of a batch of examples X with zeros. [Use np.pad](https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html). Note if you want to pad the array "a" of shape $(5,5,5,5,5)$ with `pad = 1` for the 2nd dimension, `pad = 3` for the 4th dimension and `pad = 0` for the rest, you would do:
```python
a = np.pad(a, ((0,0), (1,1), (0,0), (3,3), (0,0)), 'constant', constant_values = (..,..))
```

In [47]:
np.random.seed(1)
x = np.random.randn(4, 2, 3, 3)
print ("x[0,0] =", x[0,1,2,1])
print ('_----------_')
print (x[0,...,0])  #rows * columns (the 3 dots represents all elements in the gap)
print ('=-=-=-=-=-=-=-=-=-=-=-==-=-+++++++++++++=-=-=-=-=-=')
print (x[...,0])  #rows * columns (the 3 dots represents all elements in the gap)
print ('============')
print (x)


x[0,0] = -0.17242820755043575
_----------_
[[ 1.62434536 -1.07296862  1.74481176]
 [-0.24937038 -0.3224172  -1.09989127]]
=-=-=-=-=-=-=-=-=-=-=-==-=-+++++++++++++=-=-=-=-=-=
[[[ 1.62434536 -1.07296862  1.74481176]
  [-0.24937038 -0.3224172  -1.09989127]]

 [[ 0.04221375  1.14472371  0.90085595]
  [-0.93576943 -0.69166075 -0.84520564]]

 [[-1.11731035  0.74204416 -0.74715829]
  [-0.63699565  0.12015895 -0.35224985]]

 [[-0.20889423  0.93110208 -0.75439794]
  [-0.29809284  1.13162939 -1.39649634]]]
[[[[ 1.62434536 -0.61175641 -0.52817175]
   [-1.07296862  0.86540763 -2.3015387 ]
   [ 1.74481176 -0.7612069   0.3190391 ]]

  [[-0.24937038  1.46210794 -2.06014071]
   [-0.3224172  -0.38405435  1.13376944]
   [-1.09989127 -0.17242821 -0.87785842]]]


 [[[ 0.04221375  0.58281521 -1.10061918]
   [ 1.14472371  0.90159072  0.50249434]
   [ 0.90085595 -0.68372786 -0.12289023]]

  [[-0.93576943 -0.26788808  0.53035547]
   [-0.69166075 -0.39675353 -0.6871727 ]
   [-0.84520564 -0.67124613 -0.0126646 

In [26]:
a = np.random.randint(10,size=(2,2))
b = np.random.randint(10,size=(3,4))
print (a)
print ('_____+')
print (b)
print ('_____+')

# print (np.multiply(a,b))

print ('sum___')
print (np.sum(a))


[[0 4]
 [2 5]]
_____+
[[0 0 3 8]
 [5 3 1 4]
 [7 3 2 2]]
_____+
sum___
11


In [15]:
a = np.random.randint(4,size=(2,2))
print (a)
print (np.mean(a))

[[0 2]
 [3 3]]
2.0
