miscelenius during the course of doing week 3 assigmnet planar data model

In [1]:
import numpy as np

In [58]:
np.random.seed(9)
np.random.rand(3)

array([ 0.01037415,  0.50187459,  0.49577329])

In [60]:
np.random.rand(3)

array([ 0.41850818,  0.24810117,  0.08405965])

In [83]:
np.random.seed(2)
b = np.random.rand(10)
print (b)
print (b.sum()/3)

[ 0.4359949   0.02592623  0.54966248  0.43532239  0.4203678   0.33033482
  0.20464863  0.61927097  0.29965467  0.26682728]
1.19600339224


In [84]:
np.random.seed(2)
a = np.random.randn(10)
print (a)

print (a.sum()/3)

[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559 -0.84174737
  0.50288142 -1.24528809 -1.05795222 -0.90900761]
-2.10449980533


In [135]:
a = np.random.rand(10)
b = [1 if i > 0.5 else 0 for i in a ]
print (a)
print(b)
print (np.round(a))

[ 0.79858565  0.54334523  0.22083792  0.91845865  0.59208458  0.34623791
  0.26377853  0.91391548  0.41973546  0.54019152]
[1, 1, 0, 1, 1, 0, 0, 1, 0, 1]
[ 1.  1.  0.  1.  1.  0.  0.  1.  0.  1.]


In [137]:
a = np.random.rand(10,3)
a

array([[ 0.47140986,  0.54949682,  0.84511312],
       [ 0.9885097 ,  0.04886809,  0.23211825],
       [ 0.64331143,  0.16146656,  0.87014589],
       [ 0.21740243,  0.74175504,  0.65302051],
       [ 0.79888551,  0.03124756,  0.22957403],
       [ 0.7046275 ,  0.08756251,  0.03058948],
       [ 0.35713493,  0.58978199,  0.05222273],
       [ 0.06566367,  0.04350119,  0.39515076],
       [ 0.66842705,  0.19802711,  0.87626645],
       [ 0.4323891 ,  0.61964146,  0.29042674]])